import * as Joi from 'joi';

export const validationSchema = Joi.object({
  NODE_ENV: Joi.string().valid('development', 'test', 'production').default('development'),
  PORT: Joi.number().default(5000),
  DATABASE_URL: Joi.string().uri().required(),
  JWT_SECRET: Joi.string().min(16).required(),
  JWT_EXPIRES_IN: Joi.string().default('1d'),
  GOODWILL_API_KEY: Joi.string().allow('').optional(),
  SALVATION_ARMY_API_KEY: Joi.string().allow('').optional(),
  EBAY_APP_ID: Joi.string().allow('').optional(),
  SHIPPO_API_KEY: Joi.string().allow('').optional(),
  STRIPE_SECRET_KEY: Joi.string().allow('').optional(),
  MEDIA_STORAGE_PATH: Joi.string().default('./storage/media'),
  ENCRYPTION_KEY: Joi.string().min(16).required(),
  GOODWILL_CSV_DIRECTORY: Joi.string().default('./data/goodwill'),
  GOODWILL_BASE_URL: Joi.string().uri().default('https://shopgoodwill.com'),
  GOODWILL_BUYER_API_BASE_URL: Joi.string().uri().default('https://buyerapi.shopgoodwill.com'),
  GOODWILL_LOGIN_PAGE_PATH: Joi.string().default('/signin'),
  GOODWILL_LOGIN_PATH: Joi.string().default('/api/SignIn/Login'),
  GOODWILL_LOGIN_METHOD: Joi.string().valid('GET', 'POST').default('POST'),
  GOODWILL_LOGIN_CONTENT_TYPE: Joi.string().default('application/json'),
  GOODWILL_LOGIN_APP_VERSION: Joi.string().allow('').optional(),
  GOODWILL_LOGIN_USER_AGENT: Joi.string().allow('').optional(),
  GOODWILL_LOGIN_REMEMBER_ME: Joi.string().valid('true', 'false').default('false'),
  GOODWILL_LOGIN_ENCRYPTION_KEY: Joi.string().allow('').optional(),
  GOODWILL_USERNAME_FIELD: Joi.string().default('userName'),
  GOODWILL_PASSWORD_FIELD: Joi.string().default('password'),
  GOODWILL_LOGIN_ADDITIONAL_FIELDS: Joi.string().allow('').optional(),
  GOODWILL_LOGIN_HEADERS: Joi.string().allow('').optional(),
  GOODWILL_OPEN_CSV_PATH: Joi.string().allow('').optional(),
  GOODWILL_SHIPPED_CSV_PATH: Joi.string().allow('').optional(),
  GOODWILL_ORDER_DETAIL_JSON_PATH: Joi.string().allow('').optional(),
  GOODWILL_DETAIL_THROTTLE_MS: Joi.number().default(1500),
  GOODWILL_REQUEST_TIMEOUT: Joi.number().default(60),
  SALVATION_ARMY_BASE_URL: Joi.string().uri().default('https://www.shopthesalvationarmy.com'),
  SALVATION_ARMY_LOGIN_PATH: Joi.string().default('/Account/LogOn'),
  SALVATION_ARMY_INVOICES_URL: Joi.string().default('/Account/Invoices'),
  SALVATION_ARMY_WON_URL: Joi.string().default('/Account/Won'),
  SALVATION_ARMY_LISTING_BASE_URL: Joi.string().uri().default('https://www.shopthesalvationarmy.com'),
});
